// Builds src/lib/emojiData.ts from Unicode's emoji-test.txt: every fully
// qualified emoji in the standard order, grouped the way phones group them.
// Skin-tone and hair variants are left out (the base emoji covers them).
//
//   node scripts/gen-emoji.mjs [path-or-url-to-emoji-test.txt]

import { readFile, writeFile } from "node:fs/promises"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const source = process.argv[2] ?? "https://unicode.org/Public/emoji/latest/emoji-test.txt"
const text = source.startsWith("http") ? await (await fetch(source)).text() : await readFile(source, "utf8")

const GROUPS = {
	"Smileys & Emotion": { key: "smileys", icon: "😀" },
	"People & Body": { key: "people", icon: "👋" },
	"Animals & Nature": { key: "nature", icon: "🐶" },
	"Food & Drink": { key: "food", icon: "🍔" },
	"Activities": { key: "activity", icon: "⚽" },
	"Travel & Places": { key: "travel", icon: "🚗" },
	"Objects": { key: "objects", icon: "💡" },
	"Symbols": { key: "symbols", icon: "❤️" },
	"Flags": { key: "flags", icon: "🏳️" },
}

const MAX_VERSION = Number(process.env.EMOJI_MAX_VERSION ?? 15.0)
const out = []
let current = null
let version = ""
for (const line of text.split("\n")) {
	const v = /^# Version: ([\d.]+)/.exec(line)
	if (v) version = v[1]
	const g = /^# group: (.+)$/.exec(line)
	if (g) {
		const meta = GROUPS[g[1].trim()]
		current = meta ? { key: meta.key, icon: meta.icon, emoji: [] } : null
		if (current) out.push(current)
		continue
	}
	if (!current || line.startsWith("#") || !line.trim()) continue
	const m = /^([0-9A-F ]+?)\s*;\s*fully-qualified\s*#\s*(\S+)\s+E([\d.]+)/.exec(line)
	if (!m) continue
	// The newest emoji are missing from the fonts of most phones and
	// computers and would show as empty boxes.
	if (Number(m[3]) > MAX_VERSION) continue
	const codes = m[1].trim().split(/\s+/).map((c) => parseInt(c, 16))
	// Skin tones (1F3FB-1F3FF) and hair styles (1F9B0-1F9B3) are variants.
	if (codes.some((c) => (c >= 0x1f3fb && c <= 0x1f3ff) || (c >= 0x1f9b0 && c <= 0x1f9b3))) continue
	current.emoji.push(String.fromCodePoint(...codes))
}

const total = out.reduce((n, group) => n + group.emoji.length, 0)
if (total < 1000) throw new Error("emoji list looks wrong: " + total)
const body =
	"// Generated by scripts/gen-emoji.mjs from Unicode emoji-test.txt" + (version ? " (Emoji " + version + ")" : "") + ". Do not edit.\n\n" +
	"export type EmojiGroupKey = " + out.map((group) => JSON.stringify(group.key)).join(" | ") + "\n\n" +
	"export const EMOJI_DATA: Array<{ key: EmojiGroupKey; icon: string; emoji: string[] }> = " + JSON.stringify(out, null, "\t") + "\n"
const target = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "lib", "emojiData.ts")
await writeFile(target, body)
console.log("wrote", total, "emoji in", out.length, "groups to", target)
